language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script:
  nosetests --with-coverage --cover-package=leaf
after_success:
  coveralls
